public enum TipoToken {
    PALAVRA_RESERVADA,
    IDENTIFICADOR,
    INTEIRO,
    ATRIBUICAO,
    SOMA,
    SUBTRACAO,
    MULTIPLICACAO,
    DIVISAO,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    PONTO_E_VIRGULA,
    ERRO_LEXICO,
    EOF
}
